backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/assets/img" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/img"
collections:
  - name: "persone" # Used in routes, e.g., /admin/collections/blog
    label: Persone # Used in the UI
    folder: src/_persone # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "desc", widget: "string"}
      - {label: "Name", name: "name", widget: "text"}
      - {label:  Tags ,name: "description", widget: "text"}
      - label: "Attachments"
        name: "attachments"
        collapsed: false
        widget: "list"
        fields:
          - {label: Url, name: url, widget: string, default: "-"}